global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'finch-rest'
    consul_sd_configs:
    - server: 'consul:8500'
      services:
        - 'finch-REST'
