server:
   address: '0.0.0.0'
   port: 8585

ip2country:
  file.path: './dbip-country2.csv'   

storage:
   type: 'sqlite'   

sqlite:
   path: './finch.db'

cassandra:
   hosts: '127.0.0.1'
   keyspace: 'finch'
   consistency: 'One'
              
